"""Figure artifacts exist and the viz layer imports.

The showcase figures are committed PNG artifacts regenerated by
`python scripts/make_figures.py` (verified byte-deterministic across runs during the
build). CI does not re-render them (matplotlib rendering is slow and unnecessary against
committed fixtures), but this test guards that the artifacts the README/RESEARCH_NOTE
reference are actually present and that the viz style module is importable.
"""

from __future__ import annotations

import os

FIG_DIR = "docs/figures"
EXPECTED = [
    "01_surface_3d_BTC.png",
    "01_surface_3d_ETH.png",
    "02_smile_overlay_BTC.png",
    "02_smile_overlay_ETH.png",
    "03_atm_term_structure.png",
    "04_rr_bf_25delta.png",
    "05_crr_convergence.png",
    "06_exchange_differential.png",
]


def test_all_showcase_figures_present_and_nonempty():
    for name in EXPECTED:
        path = os.path.join(FIG_DIR, name)
        assert os.path.exists(path), f"missing figure {path} (run scripts/make_figures.py)"
        assert os.path.getsize(path) > 1000, f"figure {path} looks empty"


def test_viz_style_importable():
    import src.viz.style as style  # noqa: F401
